# Generated by Django 4.2.2 on 2023-06-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_rename_nombre_usuario_nombres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T1', models.FloatField()),
                ('WRIN', models.CharField(max_length=30)),
                ('DESCRIPCION', models.CharField(max_length=60)),
                ('CANT_A_ENVIAR', models.IntegerField()),
                ('INVENTARIO', models.IntegerField()),
            ],
        ),
    ]
