# Generated by Django 4.2.2 on 2023-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='CANT_A_ENVIAR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='INVENTARIO',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='T1',
            field=models.FloatField(null=True),
        ),
    ]
